apiVersion: skaffold/v1
kind: Config
metadata:
  name: zoo-zookeeper
build:
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
  artifacts:
    - image: zookeeper
      context: .
      sync:
        manual:
        - src: "src/*.js"
          dest: "/app"
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/deployment-dev.yaml
      - kubernetes-manifests/deployment-mongo.yaml

