---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-mongo
  labels:
    app: zookeeper
    version: v1
    group: zoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-mongo
      group: zoo
      version: v1
  template:
    metadata:
      labels:
        app: zookeeper-mongo
        group: zoo
        version: v1
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "example" 
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-mongo
spec:
  selector:
    app: zookeeper-mongo
    group: zoo
    version: v1
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017 